version: "2"
service:
  golangci-lint-version: 2.0.2

run:
  timeout: 30m
  tests: false

issues:
  max-same-issues: 0
  exclude-rules:
    - path: conversion\.go
      linters: [ineffassign]
  exclude-files:
    - ^zz_generated.*

linters:
  disable-all: true
  enable:
    - ineffassign
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - lll

linters-settings:
  nakedret:
    max-func-lines: 5
  revive:
    ignore-generated-header: false
    severity: error
    confidence: 0.8
    enable-all-rules: false
    rules:
      - name: blank-imports
        severity: error
        disabled: false
      - name: context-as-argument
        severity: error
        disabled: false
      - name: dot-imports
        severity: error
        disabled: false
      - name: error-return
        severity: error
        disabled: false
      - name: error-naming
        severity: error
        disabled: false
      - name: if-return
        severity: error
        disabled: false
      - name: increment-decrement
        severity: error
        disabled: false
      - name: var-declaration
        severity: error
        disabled: false
      - name: package-comments
        disabled: true # 禁用包注释检查
      - name: range
        severity: error
        disabled: false
      - name: receiver-naming
        severity: error
        disabled: false
      - name: time-naming
        severity: error
        disabled: false
      - name: indent-error-flow
        severity: error
        disabled: false
      - name: errorf
        severity: error
        disabled: false
      - name: context-keys-type
        severity: error
        disabled: false
      - name: error-strings
        disabled: true # 禁用错误字符串注释检查
      - name: var-naming
        disabled: true # 禁用变量命名注释检查
  staticcheck:
    checks:
      - all
      - -ST1000 # 禁用包注释检查
  lll:
    line-length: 150
    ignore-comments: true # 忽略注释的行长度限制
