version: "3.8"

services:
  registration-center:
    image: bitnami/etcd:3.5.20
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379
    ports:
      - "2379:2379"
      - "2380:2380"

  rabbit-mq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"