// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/WlayRay/order-demo/order/ent/order"
	"github.com/WlayRay/order-demo/order/ent/predicate"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (ou *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetOrderID sets the "order_id" field.
func (ou *OrderUpdate) SetOrderID(s string) *OrderUpdate {
	ou.mutation.SetOrderID(s)
	return ou
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableOrderID(s *string) *OrderUpdate {
	if s != nil {
		ou.SetOrderID(*s)
	}
	return ou
}

// ClearOrderID clears the value of the "order_id" field.
func (ou *OrderUpdate) ClearOrderID() *OrderUpdate {
	ou.mutation.ClearOrderID()
	return ou
}

// SetCustomerID sets the "customer_id" field.
func (ou *OrderUpdate) SetCustomerID(s string) *OrderUpdate {
	ou.mutation.SetCustomerID(s)
	return ou
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableCustomerID(s *string) *OrderUpdate {
	if s != nil {
		ou.SetCustomerID(*s)
	}
	return ou
}

// SetStatus sets the "status" field.
func (ou *OrderUpdate) SetStatus(s string) *OrderUpdate {
	ou.mutation.SetStatus(s)
	return ou
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableStatus(s *string) *OrderUpdate {
	if s != nil {
		ou.SetStatus(*s)
	}
	return ou
}

// ClearStatus clears the value of the "status" field.
func (ou *OrderUpdate) ClearStatus() *OrderUpdate {
	ou.mutation.ClearStatus()
	return ou
}

// SetPaymentLink sets the "payment_link" field.
func (ou *OrderUpdate) SetPaymentLink(s string) *OrderUpdate {
	ou.mutation.SetPaymentLink(s)
	return ou
}

// SetNillablePaymentLink sets the "payment_link" field if the given value is not nil.
func (ou *OrderUpdate) SetNillablePaymentLink(s *string) *OrderUpdate {
	if s != nil {
		ou.SetPaymentLink(*s)
	}
	return ou
}

// ClearPaymentLink clears the value of the "payment_link" field.
func (ou *OrderUpdate) ClearPaymentLink() *OrderUpdate {
	ou.mutation.ClearPaymentLink()
	return ou
}

// SetItems sets the "items" field.
func (ou *OrderUpdate) SetItems(m map[string]interface{}) *OrderUpdate {
	ou.mutation.SetItems(m)
	return ou
}

// Mutation returns the OrderMutation object of the builder.
func (ou *OrderUpdate) Mutation() *OrderMutation {
	return ou.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OrderUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OrderUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ou *OrderUpdate) check() error {
	if v, ok := ou.mutation.CustomerID(); ok {
		if err := order.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "Order.customer_id": %w`, err)}
		}
	}
	return nil
}

func (ou *OrderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ou.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.OrderID(); ok {
		_spec.SetField(order.FieldOrderID, field.TypeString, value)
	}
	if ou.mutation.OrderIDCleared() {
		_spec.ClearField(order.FieldOrderID, field.TypeString)
	}
	if value, ok := ou.mutation.CustomerID(); ok {
		_spec.SetField(order.FieldCustomerID, field.TypeString, value)
	}
	if value, ok := ou.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if ou.mutation.StatusCleared() {
		_spec.ClearField(order.FieldStatus, field.TypeString)
	}
	if value, ok := ou.mutation.PaymentLink(); ok {
		_spec.SetField(order.FieldPaymentLink, field.TypeString, value)
	}
	if ou.mutation.PaymentLinkCleared() {
		_spec.ClearField(order.FieldPaymentLink, field.TypeString)
	}
	if value, ok := ou.mutation.Items(); ok {
		_spec.SetField(order.FieldItems, field.TypeJSON, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetOrderID sets the "order_id" field.
func (ouo *OrderUpdateOne) SetOrderID(s string) *OrderUpdateOne {
	ouo.mutation.SetOrderID(s)
	return ouo
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableOrderID(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetOrderID(*s)
	}
	return ouo
}

// ClearOrderID clears the value of the "order_id" field.
func (ouo *OrderUpdateOne) ClearOrderID() *OrderUpdateOne {
	ouo.mutation.ClearOrderID()
	return ouo
}

// SetCustomerID sets the "customer_id" field.
func (ouo *OrderUpdateOne) SetCustomerID(s string) *OrderUpdateOne {
	ouo.mutation.SetCustomerID(s)
	return ouo
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableCustomerID(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetCustomerID(*s)
	}
	return ouo
}

// SetStatus sets the "status" field.
func (ouo *OrderUpdateOne) SetStatus(s string) *OrderUpdateOne {
	ouo.mutation.SetStatus(s)
	return ouo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableStatus(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetStatus(*s)
	}
	return ouo
}

// ClearStatus clears the value of the "status" field.
func (ouo *OrderUpdateOne) ClearStatus() *OrderUpdateOne {
	ouo.mutation.ClearStatus()
	return ouo
}

// SetPaymentLink sets the "payment_link" field.
func (ouo *OrderUpdateOne) SetPaymentLink(s string) *OrderUpdateOne {
	ouo.mutation.SetPaymentLink(s)
	return ouo
}

// SetNillablePaymentLink sets the "payment_link" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillablePaymentLink(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetPaymentLink(*s)
	}
	return ouo
}

// ClearPaymentLink clears the value of the "payment_link" field.
func (ouo *OrderUpdateOne) ClearPaymentLink() *OrderUpdateOne {
	ouo.mutation.ClearPaymentLink()
	return ouo
}

// SetItems sets the "items" field.
func (ouo *OrderUpdateOne) SetItems(m map[string]interface{}) *OrderUpdateOne {
	ouo.mutation.SetItems(m)
	return ouo
}

// Mutation returns the OrderMutation object of the builder.
func (ouo *OrderUpdateOne) Mutation() *OrderMutation {
	return ouo.mutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (ouo *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Order entity.
func (ouo *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OrderUpdateOne) check() error {
	if v, ok := ouo.mutation.CustomerID(); ok {
		if err := order.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "Order.customer_id": %w`, err)}
		}
	}
	return nil
}

func (ouo *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := ouo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.OrderID(); ok {
		_spec.SetField(order.FieldOrderID, field.TypeString, value)
	}
	if ouo.mutation.OrderIDCleared() {
		_spec.ClearField(order.FieldOrderID, field.TypeString)
	}
	if value, ok := ouo.mutation.CustomerID(); ok {
		_spec.SetField(order.FieldCustomerID, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if ouo.mutation.StatusCleared() {
		_spec.ClearField(order.FieldStatus, field.TypeString)
	}
	if value, ok := ouo.mutation.PaymentLink(); ok {
		_spec.SetField(order.FieldPaymentLink, field.TypeString, value)
	}
	if ouo.mutation.PaymentLinkCleared() {
		_spec.ClearField(order.FieldPaymentLink, field.TypeString)
	}
	if value, ok := ouo.mutation.Items(); ok {
		_spec.SetField(order.FieldItems, field.TypeJSON, value)
	}
	_node = &Order{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
