// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/WlayRay/order-demo/order/ent/order"
	"github.com/WlayRay/order-demo/order/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCustomerID is the schema descriptor for customer_id field.
	orderDescCustomerID := orderFields[2].Descriptor()
	// order.CustomerIDValidator is a validator for the "customer_id" field. It is called by the builders before save.
	order.CustomerIDValidator = orderDescCustomerID.Validators[0].(func(string) error)
}
