// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OrdersColumns holds the columns for the "orders" table.
	OrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "order_id", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "VARCHAR(50)"}},
		{Name: "customer_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "VARCHAR(50)"}},
		{Name: "status", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "VARCHAR(30)"}},
		{Name: "payment_link", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "VARCHAR(800)"}},
		{Name: "items", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "JSONB"}},
	}
	// OrdersTable holds the schema information for the "orders" table.
	OrdersTable = &schema.Table{
		Name:       "orders",
		Columns:    OrdersColumns,
		PrimaryKey: []*schema.Column{OrdersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OrdersTable,
	}
)

func init() {
}
