fallback-grpc-addr: 127.0.0.1:12305
zap-level: debug
dial-grpc-timeout: 12s

jaeger:
  url: "http://127.0.0.1:14268/api/traces"

etcd:
  endpoints:
    - "127.0.0.1:2379"
    - "127.0.0.1:2380"
    - "127.0.0.1:2381"

order:
  service-name: order
  server-to-run: http
  http-addr: 127.0.0.1:9000
  grpc-addr: 127.0.0.1:12306
  metrics-export-addr: 127.0.0.1:9123

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:9001
  grpc-addr: 127.0.0.1:12307
  metrics-export-addr: 127.0.0.1:9124

payment:
  service-name: payment
  server-to-run: http
  http-addr: 127.0.0.1:9002
  grpc-addr: 127.0.0.1:12308
  metrics-export-addr: 127.0.0.1:9125

goods:
  service-name: goods

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672
  max-retry-count: 3

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  dbname: order_demo
  search-path: order

stripe-key: "${STRIPE_KEY}"
endpoint-stripe-secret: "${ENDPOINT_STRIPE_SECRET}"