fallback-grpc-addr: 0.0.0.0:12305
zap-level: debug
dial-grpc-timeout: 12s

jaeger:
  url: "http://0.0.0.0:14268/api/traces"

etcd:
  endpoints:
    - "0.0.0.0:2379"
    - "0.0.0.0:2380"
    - "0.0.0.0:2381"

order:
  service-name: order
  server-to-run: http
  http-addr: 0.0.0.0:9000
  grpc-addr: 0.0.0.0:12306

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 0.0.0.0:9001
  grpc-addr: 0.0.0.0:12307

payment:
  service-name: payment
  server-to-run: http
  http-addr: 0.0.0.0:9002
  grpc-addr: 0.0.0.0:12308

rabbitmq:
  user: guest
  password: guest
  host: 0.0.0.0
  port: 5672

stripe-key: "${STRIPE_KEY}"
endpoint-stripe-secret: "${ENDPOINT_STRIPE_SECRET}"